name: Publish Package

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          scope: '@powersync-community'
      
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          # Pnpm 9.4 introduces this https://github.com/pnpm/pnpm/pull/7633
          # which causes workspace:^1.2.0 to be converted to 1.2.0^1.2.0
          version: 9.3
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Configure npm for GitHub Packages
        run: |
          echo "@powersync-community:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Publish package
        run: pnpm publish --no-git-checks --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}